### ISSUE TITLE
Destructured parameters not working

### ISSUE THREAD

**Issue by vjpr** [WarnerHooh/babel-plugin-parameter-decorator#24]
```
class Foo {
  async bar(@Args() {where}: ProjectsArgs) {
  }
}
```

```
xxx/node_modules/.pnpm/type-graphql@1.0.0_graphql@15.3.0/node_modules/type-graphql/dist/helpers/findType.js:12
        metadataDesignType = reflectedType[parameterIndex];
                                          ^

TypeError: Cannot read property '0' of undefined
    at Object.findType (xxx/node_modules/.pnpm/type-graphql@1.0.0_graphql@15.3.0/node_modules/type-graphql/dist/helpers/findType.js:12:43)
    at Object.getParamInfo (xxx/node_modules/.pnpm/type-graphql@1.0.0_graphql@15.3.0/node_modules/type-graphql/dist/helpers/params.js:10:49)
    at xxx/node_modules/.pnpm/type-graphql@1.0.0_graphql@15.3.0/node_modules/type-graphql/dist/decorators/Args.js:12:25
    at Object.<anonymous> (xxx/repos/gd-scratch/packages/apps/api/src/resolvers/project.resolver.ts:48:37)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module._compile (xxx/node_modules/.pnpm/pirates@4.0.1/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Object.newLoader [as .ts] (xxx/node_modules/.pnpm/pirates@4.0.1/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (xxx/repos/gd-scratch/packages/apps/api/src/schema/index.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module._compile (xxx/node_modules/.pnpm/pirates@4.0.1/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Object.newLoader [as .ts] (xxx/node_modules/.pnpm/pirates@4.0.1/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (xxx/repos/gd-scratch/packages/apps/api/src/api.ts:2:1)
```

**Comment by WarnerHooh** [comment]
Sorry for truly late, this should not be an issue with this lib, the test with destructured parameter is passed.
https://github.com/WarnerHooh/babel-plugin-parameter-decorator/blob/14953a8463190f91aa2a46af4261d1ddd8244e4f/test/src/ts/Greeter.ts#L36-L41
