### ISSUE TITLE
Compilation error when using browserlist

### ISSUE THREAD

**Issue by PDarkTemplar** [WarnerHooh/babel-plugin-parameter-decorator#6]
There is error when using browserlist, you can reproduce it by adding 
```
  "browserslist": [
    "last 1 chrome version",
    "last 1 firefox version"
],
```
to your package.json and run tests

error message:
```
TypeError: Cannot read property 'insertAfter' of null
    at C:\Dev\babel-plugin-parameter-decorator\lib\index.js:165:27
    at Array.forEach (<anonymous>)
    at C:\Dev\babel-plugin-parameter-decorator\lib\index.js:144:49
    at Array.forEach (<anonymous>)
    at PluginPass.Function (C:\Dev\babel-plugin-parameter-decorator\lib\index.js:141:44)
    at newFn (C:\Dev\babel-plugin-parameter-decorator\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (C:\Dev\babel-plugin-parameter-decorator\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Dev\babel-plugin-parameter-decorator\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\Dev\babel-plugin-parameter-decorator\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (C:\Dev\babel-plugin-parameter-decorator\node_modules\@babel\traverse\lib\context.js:118:16)
```

**Comment by WarnerHooh** [comment]
Looking into this.

**Comment by WarnerHooh** [comment]
Hi @PDarkTemplar,

I just fixed the error you mentioned, but no new version released yet. Could you please confirm if it's working for you?

You can test by this way:
```
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose" : true }],
    // "babel-plugin-parameter-decorator"
    "./babel-plugin-parameter-decorator-test.js"
  ]
}
```
Just save https://github.com/WarnerHooh/babel-plugin-parameter-decorator/blob/master/lib/index.js temporally, and replace in babelrc.

**Comment by PDarkTemplar** [comment]
Checked on my project, all working now, thank you

**Comment by WarnerHooh** [comment]
Thanks @PDarkTemplar for your confirmation, I have released a new version. Hope it works for you.

Please let me know if there's any problem.
